---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gvent-api
  labels:
    app: gvent-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gvent-api
  template:
    metadata:
      labels:
        app: gvent-api
    spec:
      containers:
      - name: api
        image: quay.io/john_mckenzie/gvent-api:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: api
            containerPort: 8000
            protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m" 
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gvent-api
  labels:
    app: gvent-api
spec:
  selector:
    app: gvent-api
  type: ClusterIP
  sessionAffinity: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
