openapi: "3.0.0"
info:
  title: gvent-api
  description: Provides a REST API to manage the system data model.
  contact:
    name: John McKenzie
    url: https://mkz.io
    email: jmckind@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths:
  /events:
    get:
      summary: List all events
      operationId: listEvents
      tags:
        - events
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of events
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Events"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Event:
      allOf:
        - $ref: '#/components/schemas/NewEvent'
        - required:
          - id
          properties:
            id:
              type: integer
              format: int64
    NewEvent:
      required:
        - name
      properties:
        name:
          type: string
        tag:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
